# Generated by Django 4.0.5 on 2022-07-16 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bookapp/covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='bookapp/pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
